version: '2'

services:
  postgres:
    # container_name: postgres-db
    image: 'bitnami/postgresql:latest'
    restart: always
    ports:
      - 5432:5432
    volumes:
      - './postgres-data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - pgadmin

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin
    ports:
      - "5433:80"
    networks:
      - pgadmin

  sonarqube:
    image: sonarqube:community
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonar-data/data:/opt/sonarqube/data
      - ./sonar-data/extensions:/opt/sonarqube/extensions
      - ./sonar-data/logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - pgadmin

networks:
  pgadmin:
    driver: bridge



# sonar login user:pwd - admin:sonar
# posgress db:user:pwd - test:admin:admin , sonar:sonar:sonar, postgres:postgres:postgres
