# Note this is not stabilized use the zk folder zk-deployment for kafka
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-zk
spec:
  selector:
    matchLabels:
      app: k8s-zk
  template:
    metadata:
      labels:
        app: k8s-zk
    spec:
      containers:
      - name: k8s-zk
        image: confluentinc/cp-zookeeper:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        envFrom:
          - configMapRef:
              name: zk-env-conf
        ports:
        - containerPort: 2181
        
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-env-conf
data:
  ZOOKEEPER_CLIENT_PORT: '2181'
  ZOOKEEPER_TICK_TIME: '2000'

---

# apiVersion: v1
# kind: Service
# metadata:
#   name: zk-service-lb
# spec:
#   selector:
#     app: k8s-zk
#   type: LoadBalancer
#   ports:
#   - port: 22181
#     targetPort: 2181

# ---

apiVersion: v1
kind: Service
metadata:
  name: zk-service-cp
spec:
  selector:
    app: k8s-zk
  clusterIP: None
  type: ClusterIP
  ports:
  - port: 2181
    targetPort: 2181

